apiVersion: v1
kind: Secret
metadata:
  name: secret-db-password
  namespace: dn  # Optional,default isusually fine
type: Opaque
data:
  secret-db-password-key: SG93YXJkIzg3 # The base64-encoded password